/* GENERATED by scripts/gen-icons.mjs — do not edit by hand. */
/* 73 icons from the design handoff. All strokes normalised to
   currentColor, so colour is controlled by CSS alone (digest §8). */

import Arc from "../icons/Arc.svg?react";
import AutoPlane from "../icons/Auto-Plane.svg?react";
import Boolean from "../icons/Boolean.svg?react";
import Box from "../icons/Box.svg?react";
import Chair from "../icons/Chair.svg?react";
import Check from "../icons/Check.svg?react";
import ChevronDown from "../icons/Chevron-Down.svg?react";
import Circle from "../icons/Circle.svg?react";
import Column from "../icons/Column.svg?react";
import Cone from "../icons/Cone.svg?react";
import Cylinder from "../icons/Cylinder.svg?react";
import Deform from "../icons/Deform.svg?react";
import Dimension from "../icons/Dimension.svg?react";
import Door from "../icons/Door.svg?react";
import Extrude from "../icons/Extrude.svg?react";
import ExtrudePlus from "../icons/Extrude-Plus.svg?react";
import Eye from "../icons/Eye.svg?react";
import Eyedropper from "../icons/Eyedropper.svg?react";
import Fit from "../icons/Fit.svg?react";
import Flyover from "../icons/Flyover.svg?react";
import FromFace from "../icons/From-Face.svg?react";
import Grid from "../icons/Grid.svg?react";
import Lamp from "../icons/Lamp.svg?react";
import LayerPlane from "../icons/Layer-Plane.svg?react";
import Layers from "../icons/Layers.svg?react";
import Line from "../icons/Line.svg?react";
import LinePoints from "../icons/Line-Points.svg?react";
import Lock from "../icons/Lock.svg?react";
import Loft from "../icons/Loft.svg?react";
import Moon from "../icons/Moon.svg?react";
import NURBS from "../icons/NURBS.svg?react";
import Pan from "../icons/Pan.svg?react";
import Perspective from "../icons/Perspective.svg?react";
import Plane from "../icons/Plane.svg?react";
import Plus from "../icons/Plus.svg?react";
import Polygon from "../icons/Polygon.svg?react";
import PushPullAdd from "../icons/PushPull-Add.svg?react";
import PushPullSubtract from "../icons/PushPull-Subtract.svg?react";
import QPPageBoundary from "../icons/QP-Page-Boundary.svg?react";
import QPRulers from "../icons/QP-Rulers.svg?react";
import Rectangle from "../icons/Rectangle.svg?react";
import Redo from "../icons/Redo.svg?react";
import Roof from "../icons/Roof.svg?react";
import SavedViews from "../icons/Saved-Views.svg?react";
import ScreenPlane from "../icons/Screen-Plane.svg?react";
import Search from "../icons/Search.svg?react";
import Select from "../icons/Select.svg?react";
import Shaded from "../icons/Shaded.svg?react";
import Slab from "../icons/Slab.svg?react";
import Snap from "../icons/Snap.svg?react";
import SnapAngle from "../icons/Snap-Angle.svg?react";
import SnapGrid from "../icons/Snap-Grid.svg?react";
import SnapIntersection from "../icons/Snap-Intersection.svg?react";
import SnapObject from "../icons/Snap-Object.svg?react";
import SnapSmartPoints from "../icons/Snap-Smart-Points.svg?react";
import SnapTangent from "../icons/Snap-Tangent.svg?react";
import Sofa from "../icons/Sofa.svg?react";
import Solids from "../icons/Solids.svg?react";
import Sphere from "../icons/Sphere.svg?react";
import Stair from "../icons/Stair.svg?react";
import Stairs from "../icons/Stairs.svg?react";
import Sun from "../icons/Sun.svg?react";
import Sweep from "../icons/Sweep.svg?react";
import Symmetric from "../icons/Symmetric.svg?react";
import Table from "../icons/Table.svg?react";
import Text from "../icons/Text.svg?react";
import Tree from "../icons/Tree.svg?react";
import Undo from "../icons/Undo.svg?react";
import ViewList from "../icons/View-List.svg?react";
import ViewThumbnails from "../icons/View-Thumbnails.svg?react";
import Wall from "../icons/Wall.svg?react";
import Window from "../icons/Window.svg?react";
import Zoom from "../icons/Zoom.svg?react";

export const ICONS = {
  "Arc": Arc,
  "Auto-Plane": AutoPlane,
  "Boolean": Boolean,
  "Box": Box,
  "Chair": Chair,
  "Check": Check,
  "Chevron-Down": ChevronDown,
  "Circle": Circle,
  "Column": Column,
  "Cone": Cone,
  "Cylinder": Cylinder,
  "Deform": Deform,
  "Dimension": Dimension,
  "Door": Door,
  "Extrude": Extrude,
  "Extrude-Plus": ExtrudePlus,
  "Eye": Eye,
  "Eyedropper": Eyedropper,
  "Fit": Fit,
  "Flyover": Flyover,
  "From-Face": FromFace,
  "Grid": Grid,
  "Lamp": Lamp,
  "Layer-Plane": LayerPlane,
  "Layers": Layers,
  "Line": Line,
  "Line-Points": LinePoints,
  "Lock": Lock,
  "Loft": Loft,
  "Moon": Moon,
  "NURBS": NURBS,
  "Pan": Pan,
  "Perspective": Perspective,
  "Plane": Plane,
  "Plus": Plus,
  "Polygon": Polygon,
  "PushPull-Add": PushPullAdd,
  "PushPull-Subtract": PushPullSubtract,
  "QP-Page-Boundary": QPPageBoundary,
  "QP-Rulers": QPRulers,
  "Rectangle": Rectangle,
  "Redo": Redo,
  "Roof": Roof,
  "Saved-Views": SavedViews,
  "Screen-Plane": ScreenPlane,
  "Search": Search,
  "Select": Select,
  "Shaded": Shaded,
  "Slab": Slab,
  "Snap": Snap,
  "Snap-Angle": SnapAngle,
  "Snap-Grid": SnapGrid,
  "Snap-Intersection": SnapIntersection,
  "Snap-Object": SnapObject,
  "Snap-Smart-Points": SnapSmartPoints,
  "Snap-Tangent": SnapTangent,
  "Sofa": Sofa,
  "Solids": Solids,
  "Sphere": Sphere,
  "Stair": Stair,
  "Stairs": Stairs,
  "Sun": Sun,
  "Sweep": Sweep,
  "Symmetric": Symmetric,
  "Table": Table,
  "Text": Text,
  "Tree": Tree,
  "Undo": Undo,
  "View-List": ViewList,
  "View-Thumbnails": ViewThumbnails,
  "Wall": Wall,
  "Window": Window,
  "Zoom": Zoom,
} as const;

export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS) as IconName[];
